name: Build Kernel

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

    steps:
      - name: Set CONFIG Environment Variable
        run: |
          # Set CONFIG
          CONFIG="$GITHUB_WORKSPACE"

          # Set CONFIG as an environment variable for future steps
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV

      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Checkout kernel source repository
        uses: actions/checkout@v7
        with:
          repository: 'Rocky7842/android_kernel_xiaomi_sm8350'
          ref: 'lineage-23.2'
          fetch-depth: 1
          path: common

      - name: Merge files
        run: |
          cd $GITHUB_WORKSPACE/common
          find ../ -maxdepth 1 -type f -exec cp -v {} ./ \;

      - name: Update and install required packages
        run: |
          sudo apt update
          sudo apt install -y libc6-dev clang gcc-multilib flex bison libssl-dev bc python3 zip unzip lld llvm p7zip-full ccache jq

      - name: Set up ccache
        run: |
          ccache --version
          ccache --max-size=2G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

      - name: Restore ccache from cache
        uses: actions/cache/restore@v6
        with:
          path: ~/.ccache
          key: ccache-${{ github.sha }}
          restore-keys: |
            ccache-

      - name: Prepare magiskboot
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          cd $GITHUB_WORKSPACE/output
          curl -L -o magiskboot.7z "https://github.com/xiaoxindada/magisk_bins_ndk/releases/download/magisk_bins-30700-9d863eca67a437a2a672a4a5ec1f8374e5a66158/magisk_bins.7z"
          7z x magiskboot.7z
          cp ./native/out/x86_64/magiskboot .
          chmod +x magiskboot
          rm -rf ./out

      - name: Prepare required toolchains
        run: |
          mkdir -p $GITHUB_WORKSPACE/toolchains
          cd $GITHUB_WORKSPACE/toolchains
          git clone https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 --branch=main-kernel-build-2024 --depth=1
          git clone https://android.googlesource.com/platform/system/libufdt --branch=main --depth=1

      - name: Remove unnecessary tools
        run: |
          cd $GITHUB_WORKSPACE/toolchains/linux-x86
          latest_clang=$(find . -maxdepth 1 -type d -name "clang-r*" | sed 's|.*/||' | sort -Vr | head -n 1)
          echo "Latest Clang version detected: $latest_clang"
          
          for dir in clang-r*; do
            if [[ "$dir" != "$latest_clang" ]]; then
              echo "Removing $dir"
              rm -rf "$dir"
            fi
          done
          # Export path
          export PATH="$GITHUB_WORKSPACE/toolchains/linux-x86/$latest_clang/bin:$PATH"

      - name: Clone Other Dependencies
        run: |
          cd "$GITHUB_WORKSPACE"
          git clone https://github.com/WildPlusKernel/kernel_patches.git

      - name: Apply ptrace patch
        run: |
          cd "$GITHUB_WORKSPACE/common"
          patch -p1 -F 3 < "../kernel_patches/gki_ptrace.patch"

      - name: Add KernelSU
        run: |
          cd "$GITHUB_WORKSPACE/common"
          curl -LSs "https://raw.githubusercontent.com/MirahSyakilla/KSUN/main/kernel/setup.sh" | bash -s susfs+nomount-hookless
          echo "KSU_REPO=https://github.com/KernelSU-Next/KernelSU-Next" >> $GITHUB_ENV
          cd KernelSU-Next
          echo "KSU_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "KSU_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          KSU_GIT_VER=$(git rev-list --count HEAD)
          echo "KSU_VER=$(expr 30000 + ${KSU_GIT_VER})" >> $GITHUB_ENV
          cd ..
          sed -i 's|#include <linux/version.h>|#include <linux/version.h>\n#include <linux/ratelimit.h>|' ./drivers/kernelsu/extras.c

      # - name: Apply Hooks Patches
      #   run: |
      #     cd "$GITHUB_WORKSPACE/common"
      #     
      #     echo "Applying hooks..."
      #     cp ../kernel_patches/next/scope_min_manual_hooks_v1.6.patch ./
      #     sed -i 's|static int do_execve(struct filename \*filename,|int do_execve(struct filename *filename,|' ./scope_min_manual_hooks_v1.6.patch
      #     patch -p1 -F 3 < ./scope_min_manual_hooks_v1.6.patch

      - name: Set Kernel Configuration Variables
        run: |
          cd "$CONFIG"
          echo "Initializing kernel configuration..."
          echo "DEFCONFIG=./common/arch/arm64/configs/lisa_defconfig" >> $GITHUB_ENV
          
          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki

      - name: Configure KernelSU Core
        run: |
          cd "$CONFIG"
          # KernelSU Configuration
          echo "# KernelSU Configuration" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KSU=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KSU_KPROBES_HOOK=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KSU_HACK_ARM64_BRANCH_LINK=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KSU_KPROBES_NOMOUNT=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KSU_KPROBES_SUSFS=y" >> "${{ env.DEFCONFIG }}"
          
          echo "CONFIG_KALLSYMS=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KALLSYMS_ALL=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KPROBES=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_KRETPROBES=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_HAVE_KPROBES=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_HAVE_KRETPROBES=y" >> "${{ env.DEFCONFIG }}"

      - name: Configure Mountify Support
        run: |
          cd "$CONFIG"
          # Mountify Support
          echo "# Mountify Support" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TMPFS_XATTR=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> "${{ env.DEFCONFIG }}"

      - name: Configure Networking
        run: |
          cd "$CONFIG"
          # Networking Configuration
          echo "# Networking Configuration" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> "${{ env.DEFCONFIG }}"

      - name: Configure TCP Congestion Control
        run: |
          cd "$CONFIG"
          # BBR TCP Congestion Control
          echo "# BBR TCP Congestion Control" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TCP_CONG_BBR=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_NET_SCH_FQ=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TCP_CONG_BIC=n" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_TCP_CONG_HTCP=n" >> "${{ env.DEFCONFIG }}"

      - name: Configure IPSet Support
        run: |
          cd "$CONFIG"
          # IPSet support
          echo "# IPSet Support" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_MAX=65534" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_BITMAP_IP=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_BITMAP_PORT=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IP=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IPMARK=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IPPORT=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_IPMAC=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_MAC=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_NET=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_NETNET=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_NETPORT=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_IP_SET_LIST_SET=y" >> "${{ env.DEFCONFIG }}"

      - name: Configure Build Optimization
        run: |
          cd "$CONFIG"
          # Build Optimization Configuration
          echo "# Build Optimization Configuration" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_LTO_CLANG_THIN=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_LTO_CLANG=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3=n" >> "${{ env.DEFCONFIG }}"
          echo "CONFIG_OPTIMIZE_INLINING=y" >> "${{ env.DEFCONFIG }}"

      - name: Prepare Build
        run: |
          cd $GITHUB_WORKSPACE/common/scripts
          cp $GITHUB_WORKSPACE/toolchains/libufdt/utils/src/mkdtboimg.py mkdtboimg.py
          sed -i 's|python2|python3|' Makefile.lib

      - name: Build Kernel Configuration
        run: |
          cd "$GITHUB_WORKSPACE/common"
          mkdir out
          ARCH=arm64 scripts/kconfig/merge_config.sh -O out -m \
            arch/arm64/configs/vendor/lahaina-qgki_defconfig \
            arch/arm64/configs/vendor/debugfs.config \
            arch/arm64/configs/vendor/xiaomi_QGKI.config \
            arch/arm64/configs/lisa_defconfig
          make -j$(nproc --all) O=out ARCH=arm64 olddefconfig \
            LLVM=1 \
            LLVM_IAS=1 \
            HOSTLD=ld.lld \
            CC="/usr/bin/ccache clang" \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          cat out/include/generated/autoconf.h

      - name: Build Kernel
        id: build
        run: |
          cd $GITHUB_WORKSPACE/common
          make -j$(nproc --all) O=out ARCH=arm64 \
            LLVM=1 \
            LLVM_IAS=1 \
            HOSTLD=ld.lld \
            CC="/usr/bin/ccache clang" \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_COMPAT=arm-linux-gnueabi-
          cp $GITHUB_WORKSPACE/common/out/arch/arm64/boot/Image $GITHUB_WORKSPACE/output

      - name: Always Save ccache to cache
        if: success() || steps.build.conclusion == 'failure'
        uses: actions/cache/save@v6
        with:
          path: ~/.ccache
          key: ccache-${{ github.sha }}

      - name: Build Kernel Info
        run: |
          cd $GITHUB_WORKSPACE/common
          export version=$(make -j$(nproc --all) -s O=out kernelrelease)
          export version=$(echo ${version/-dirty/-ksun-g${{ env.KSU_SHORT_SHA }}})
          echo "RELEASE_TAG=$version" >> $GITHUB_ENV
          ccache --show-stats
          df -H .

      - name: Pack up
        run: |
          cd $GITHUB_WORKSPACE/output
          mv Image kernel
          7z a kernel.7z kernel

      - name: Upload Kernel
        uses: actions/upload-artifact@v7
        with:
          name: kernel
          path: output/kernel

      - name: Upload Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body: |
            Kernel ${{ env.RELEASE_TAG }}
            KernelSU Next ${{ env.KSU_VER }} [${{ env.KSU_SHORT_SHA }}](${{ env.KSU_REPO }}/commit/${{ env.KSU_SHA }})
          files: |
            output/kernel
            output/kernel.7z
